### ISSUE TITLE
[README.md] compilation instructions to be improved

### ISSUE THREAD

**Issue by akuropka** [peseoane/linux-wsl#12]
I think, the code should be slightly different:

export KCFLAGS="-**O**2 -mtune=native -pipe" KCPPFLAGS="-**O**2 -mtune=native -pipe"
make all

**Comment by peseoane** [comment]
> I think, the code should be slightly different:
> 
> export KCFLAGS="-**O**2 -mtune=native -pipe" KCPPFLAGS="-**O**2 -mtune=native -pipe"
> make all

Thanks, changes added! :)
