### ISSUE TITLE
Include 'microsoft' in kernel version string

### ISSUE THREAD

**Issue by wizonesolutions** [peseoane/linux-wsl#7]
Would it be possible to still include `microsoft` in the kernel version string (shown in `/proc/version`)?

Vagrant inside of WSL 2 looks for this in order to detect if it's running inside of WSL 2 and should thus use VirtualBox on Windows.

**Comment by peseoane** [comment]
I think it's better to use the official repository for that, the advantage of this one is that it's a WSL2 without a lot of Microsoft bloatware.

I recommend theirs, please go to https://github.com/microsoft/WSL2-Linux-Kernel or fork. be free
