### ISSUE TITLE
kernel 5.12.13 is still showing as 5.12.12 when you uname -r

### ISSUE THREAD

**Issue by abun880007** [peseoane/linux-wsl#9]
Hi Just to let you know that the kernel 5.12.13 is still showing as 5.12.12 when you uname -r

**Comment by Yoanf26** [comment]
Hello

5.12.13 showing when uname -r for me.

**Comment by peseoane** [comment]
Hello.

You're right, I must have not done the mix right this time and updated correctly.

Next release I promise to double check.

However, I have checked the whole source code and it is subversion 13, and to fix it I should remove the whole tag.

I think it's a minor bug, thanks for the warning and as soon as I get back from work this Monday I'll fix it.

Thank you very much for the warning.
